### ISSUE TITLE
Cryptic error if keywords is an empty list

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1002]
## 1) Bug

If the `keywords` argument to `NWBFile` is an empty list, this confusing error message is returned:
`TypeError: incorrect type for 'dtype' (got 'function', expected 'type, dtype, str or list')`

Fix: make error message say something like "keywords argument cannot be an empty list"

### Steps to Reproduce
```python
from pynwb import NWBFile, NWBHDF5IO
from datetime import datetime

nwbfile = NWBFile(session_description='ADDME',
                  identifier='ADDME',
                  session_start_time=datetime.now().astimezone(),
                  keywords=[])

with NWBHDF5IO('test_keywords.nwb', 'w') as io:
    io.write(nwbfile)
```
### Environment
Please describe your environment according to the following bullet points.
- **Python Executable:** Conda
- **Python Version:** Python 3.7
- **Operating System:** Windows
- **Pynwb Version:** latest dev

**Comment by rly** [comment]
Other places where a list is accepted should also be checked for this. The change probably needs to happen in HDMF.

**Comment by bendichter** [comment]
Strange. Does the same occur with an empty tuple?

**Comment by stamatiad** [comment]
I can confirm that a git bisect places it right when HDMF was introduced #850, 2cbb725. Investigating...

**Comment by bendichter** [comment]
This bug no longer occurs, but instead you get this:
```
root pynwb.file.NWBFile at 0x140595904087136
Fields:
  file_create_date: [datetime.datetime(2022, 11, 10, 15, 43, 25, 331580, tzinfo=tzoffset(None, -18000))]
  identifier: ADDME
  keywords: <HDF5 dataset "keywords": shape (0,), type "|O">
  session_description: ADDME
  session_start_time: 2022-11-10 15:43:25.330690-05:00
  timestamps_reference_time: 2022-11-10 15:43:25.330690-05:00
```

`keywords` is saved as an empty dataset. Is this the behavior we want, or would we prefer to catch this and replace it with `None` so nothing is written?
