### ISSUE TITLE
SpatialSeries should accept unit argument

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1174]
From the hackathon:

The `SpatialSeries` constructor does not accept a `'unit'` argument and fixes its value to `'meters'`. However, the spec says that the `'unit'` attribute is 1) optional and 2) has a default value of `'meters'`, not a fixed value.

```yaml
    - name: unit
      dtype: text
      default_value: meters
      doc: ...
      required: false
```

`'SpatialSeries'` is the recommended type for storing angular data (i.e., where the unit needs to be set to 'radians' or 'degrees'), so it needs to be settable in the constructor.
