### ISSUE TITLE
CorrectedImageStack should enforce required names for child objects 

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#1305]
## Description

The NWB schema for `CorrectedImageStack` requires that its child groups 'corrected' (ImageSeries) and 'xy_translation' (TimeSeries) have those names, but PyNWB does not enforce those names. This allows for the creation of files that do not validate:
(acquisition/CorrectedImageStack): missing data type TimeSeries

YAML:
```yaml
- neurodata_type_def: CorrectedImageStack
  neurodata_type_inc: NWBDataInterface
  doc: Reuslts from motion correction of an image stack.
  groups:
  - name: corrected
    neurodata_type_inc: ImageSeries
    doc: Image stack with frames shifted to the common coordinates.
  - name: xy_translation
    neurodata_type_inc: TimeSeries
    doc: Stores the x,y delta necessary to align each frame to the common coordinates,
      for example, to align each frame to a reference image.
  ...
```

## Environment

    Python Executable: Conda
    Python Version: Python 3.7
    Operating System: Windows
    HDMF Version: dev

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [ ] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
