### ISSUE TITLE
[Feature]: Support `get_class` with arbitrary recursion depth

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#1664]
### What would you like to see added to PyNWB?

I am running into a problem automatically generating an extension I am creating of the form:

```yaml
groups: 
  - neurodata_type: BioSample
    groups:
     - name: isDerivedFrom
       links:
        - type: BioSample
```

To make `get_class` work on this, we'd need to support arbitrary depth recursion, which is not currently supported.

### What solution would you like?

modifications to `get_class`.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this change was not already [requested](https://github.com/NeurodataWithoutBorders/pynwb/issues)?
