### ISSUE TITLE
[Bug]: Suite2p NWB files

### ISSUE THREAD

**Issue by jeromelecoq** [NeurodataWithoutBorders/pynwb#1667]
### What happened?

Not sure if it belongs here but suite2p seems to generate non-compliant NWB files. 

Here is a copy of my validation errors. Some are due to me not adding the info but the GUI does not allow this directly. 

0  CRITICAL
===========

0.0  ./: check_unique_identifiers - 'NWBFile' object at location '/'
       Message: The identifier '../data' is used across the .nwb files: ['Rorb-IRES2-Cre_590168381_590168385.nwb', 'Rorb-IRES2-Cre_590168381_590565013.nwb']. The identifier of any NWBFile should be a completely unique value - we recommend using uuid4 to achieve this.

0.1  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_image_series_external_file_valid - 'TwoPhotonSeries' object at location '/acquisition/TwoPhotonSeries'
       Message: The external file '../data/merged_movie.h5' does not exist. Please confirm the relative location to the NWBFile.

0.2  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_subject_exists - 'NWBFile' object at location '/'
       Message: Subject is missing.

0.3  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_roi_response_series_dims - 'RoiResponseSeries' object at location '/processing/ophys/Neuropil/Neuropil'
       Message: The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.

0.4  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_roi_response_series_dims - 'RoiResponseSeries' object at location '/processing/ophys/Fluorescence/Fluorescence'
       Message: The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.

0.5  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_roi_response_series_dims - 'RoiResponseSeries' object at location '/processing/ophys/Deconvolved/Deconvolved'
       Message: The second dimension of data does not match the length of rois, but instead the first does. Data is oriented incorrectly and should be transposed.

1  BEST_PRACTICE_VIOLATION
==========================

1.6  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_data_orientation - 'RoiResponseSeries' object at location '/processing/ophys/Neuropil/Neuropil'
       Message: Data may be in the wrong orientation. Time should be in the first dimension, and is usually the longest dimension. Here, another dimension is longer.

1.7  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_data_orientation - 'RoiResponseSeries' object at location '/processing/ophys/Fluorescence/Fluorescence'
       Message: Data may be in the wrong orientation. Time should be in the first dimension, and is usually the longest dimension. Here, another dimension is longer.

1.8  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_data_orientation - 'RoiResponseSeries' object at location '/processing/ophys/Deconvolved/Deconvolved'
       Message: Data may be in the wrong orientation. Time should be in the first dimension, and is usually the longest dimension. Here, another dimension is longer.

2  BEST_PRACTICE_SUGGESTION
===========================

2.9  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'RoiResponseSeries' object at location '/processing/ophys/Neuropil/Neuropil'
       Message: Description ('no description') is a placeholder.

2.10  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'RoiResponseSeries' object at location '/processing/ophys/Fluorescence/Fluorescence'
        Message: Description ('no description') is a placeholder.

2.11  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'RoiResponseSeries' object at location '/processing/ophys/Deconvolved/Deconvolved'
        Message: Description ('no description') is a placeholder.

2.12  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'Images' object with name 'Backgrounds_0'
        Message: Description ('no description') is a placeholder.

2.13  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'GrayscaleImage' object with name 'meanImg'
        Message: Description is missing.

2.14  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'GrayscaleImage' object with name 'max_proj'
        Message: Description is missing.

2.15  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'GrayscaleImage' object with name 'Vcorr'
        Message: Description is missing.

2.16  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_description - 'TwoPhotonSeries' object at location '/acquisition/TwoPhotonSeries'
        Message: Description ('no description') is a placeholder.

2.17  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_small_dataset_compression - 'RoiResponseSeries' object at location '/processing/ophys/Neuropil/Neuropil'
        Message: data is not compressed. Consider enabling compression when writing a dataset.

2.18  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_small_dataset_compression - 'RoiResponseSeries' object at location '/processing/ophys/Fluorescence/Fluorescence'
        Message: data is not compressed. Consider enabling compression when writing a dataset.

2.19  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_small_dataset_compression - 'RoiResponseSeries' object at location '/processing/ophys/Deconvolved/Deconvolved'
        Message: data is not compressed. Consider enabling compression when writing a dataset.

2.20  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_experimenter_exists - 'NWBFile' object at location '/'
        Message: Experimenter is missing.

2.21  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_experiment_description - 'NWBFile' object at location '/'
        Message: Experiment description is missing.

2.22  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_institution - 'NWBFile' object at location '/'
        Message: Metadata /general/institution is missing.

2.23  Rorb-IRES2-Cre_590168381_590168385.nwb and 1 other file: check_keywords - 'NWBFile' object at location '/'
        Message: Metadata /general/keywords is missing.

### Steps to Reproduce

```python
Load a movie into suite2p, run segmentation and save the NWB file
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.7

### Package Versions

From my docker :
RUN pip install -U --no-cache-dir \
    pynwb==2.2.0 \
    suite2p==0.11.1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by bendichter** [comment]
@jeromelecoq thanks for this. Best practices have come a long way since we built the NWB export years ago. Our latest way to write files from suite2p is write the default format and then use NeuroConv [`Suite2pSegmentationInterface`](https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/segmentation/suite2p.html). This method has the advantage of allowing you to easily combine suite2p data with other data, such as the raw TIFF stack and/or trial events

**Comment by jeromelecoq** [comment]
Can you clarify a little more? 
Suite2p does output NWB files. What should be given to NeuroConv? The NWB from suite2p or the binary files from suite2p?

**Comment by bendichter** [comment]
the binary files from suite2p

**Comment by oruebel** [comment]
> Best practices have come a long way since we built the NWB export years ago. Our latest way to write files from suite2p is write the default format and then use NeuroConv

@bendichter does this mean we should engage with suite2p to update the write there?

**Comment by rly** [comment]
I encountered this last week when comparing suite2p and caiman support for NWB. Does it make sense for suite2p (and similar processing/analysis tools) to accept a non-NWB file and create an NWB file? suite2p (and similar tools) does not handle information about the full experiment. For example, it does not have information about the subject, device, experimenter, session ID, etc., so when it makes an NWB file, that file does not conform to best practices in several ways and is not really publishable or usable on its own. suite2p could put placeholders for those, but NWB really does not make it easy to change those placeholders once set. suite2p could ask the user for those, but that's a burden on suite2p to develop and maintain, just to support NWB output. 

If you already have an NWB file with your raw data and experimental metadata, suite2p does not append to it, but creates its own NWB file, and merging NWB files is unfortunately not straightforward.

It seems to me that using neuroconv to read a processing tool's native output and create an NWB file that merges that output with experimental metadata required by neuroconv is a better strategy. OR the tool should simply append data to an input NWB file that should have all the experimental metadata present already. Tools should not create NWB files with only their output; that leads to the confusion above where the output is technically a valid NWB file but is an incomplete and not very useful NWB file.

**Comment by jeromelecoq** [comment]
From a user perspective, I think it is reasonable to ask that the ecosystem of tools work well together. If suite2p generates an NWB file it should be possible to push the data to Dandi eventually. In this particular case, I ran 40ish processing jobs and saved the NWB file from Suite2p in the hope to eventually push it to Dandi. Having to go back to the raw feels like the tool are not working well together. 

I feel like suite2p could create a barebone NWB with fields that are to be filled later on before submission, if that is at all possible. Currently it is mostly failing validation because of **transpose** issues. I would not mind merging NWB files from different machine for example.

**Comment by bendichter** [comment]
@jeromelecoq 
> If suite2p generates an NWB file it should be possible to push the data to Dandi eventually.

Agreed. This integration was created long before the DANDI requirements were in place so we'll need to fix them. And we definitely need to fix any transpose issues.

@rly you make some good points.

It's certainly easier on our side to maintain conversion tools in NeuroConv so we can adjust them as requirements are made more stringent by DANDI and test them all of compliance with CI. All of the different format conversions share a lot of functions so that is easier than maintaining exports across many libraries. We will continue to do that, but there remains the question of whether suite2p should provide an option to export to NWB.

It makes sense for suite2p to offer the functionality of appending to an existing NWB file and it might be easier to build a DANDI-compliant. I think it also makes sense to have suite2p output just the processed data, though I agree it would take substantial effort to get this to the point where it would be able to support non-filler metadata for all the required fields. Maybe that's more work than it's worth when you multiply it out by all the analysis tools in the ecosystem. NeuroConv might be able to help with this. We could have it as an optional requirement and dynamically import some of our internal functions when an NWB export is requested, but that's a bit outside the original scope of NeuroConv

**Comment by oruebel** [comment]
> It makes sense for suite2p to offer the functionality of appending to an existing NWB file and it might be easier to build a DANDI-compliant. I think it also makes sense to have suite2p output just the processed data, though I agree it would take substantial effort to get this to the point where it would be able to support non-filler metadata for all the required fields.

An alternative option is to, instead of appending to the source file, to export the source file to a new file such that the new file would only contain links to original file (rather an copying data) and then appending to that file. In this way the original file would not be modified while from a user perspective the new file would look like all data is in one file. Similarly, one could also use 3 files: 1) the input file with the raw data, 2) a file with just the processing results, and 3) a third file that would consists of just external links to put the data from the data files together.

This approach with external HDF5 links is already possible with current features, however, it may be worth discussing whether a simpler sub-filing approach may be needed to make the integration of processing tools easier. E.g., I could imagine that one could place subfiles (which would just add new data, e.g., new TimeSeries) in a subfolder along with a main NWB file to then merge the files dynamically on read, or have some other ways to break up and merge NWB files.

**Comment by jeromelecoq** [comment]
The following code fixes MOST of the critical errors.
```
import numpy as np
from pynwb import NWBHDF5IO
from pynwb.ophys import RoiResponseSeries
import h5py
from pynwb.file import Subject

# Open the NWB file for writing
with NWBHDF5IO('../old/Rorb-IRES2-Cre_590168381_590565013.nwb', 'r') as read_io:
    # Create a new NWB file object
    nwbfile = read_io.read()

    nwbfile.subject = Subject(
    subject_id="001",
    age="P100D/P130D",
    description="Rorb-IRES2-Cre",
    species="Mus musculus",
    sex="M",
    )

    nwbfile.acquisition.pop(nwbfile.acquisition['TwoPhotonSeries'].name)
    nwb_object = {}
    roi_series = {}
    for key in ['Neuropil', 'Deconvolved']:# 'Fluorescence']:
        nwb_object[key] = nwbfile.processing['ophys'][key]
        roi_series[key] = nwbfile.processing['ophys'][key][key]

        # Get the data array from a RoiResponseSeries object
        local_data = nwbfile.processing['ophys'][key][key].data[:]

        # Transpose the array
        transposed_local_data = np.transpose(local_data, (1, 0))

        nwb_object[key].roi_response_series.pop(roi_series[key].name)

        roi_series[key].reset_parent()
        
        for child in roi_series[key].children:
            child.reset_parent()   

        new_response_roi = RoiResponseSeries(
            name=roi_series[key].name,
            data=transposed_local_data,
            unit=roi_series[key].unit,
            rois=roi_series[key].rois,
            timestamps=roi_series[key].timestamps,
            rate=roi_series[key].rate,
            description=key
        )

        nwb_object[key].add_roi_response_series(new_response_roi)

    # Update the data in the RoiResponseSeries object

    # call the export method to write the modified NWBFile instance to a new file path.
    # the original file is not modified
    with NWBHDF5IO('Rorb-IRES2-Cre_590168381_590565013_new.nwb', mode='w') as export_io:
        export_io.export(src_io=read_io, nwbfile=nwbfile)

    with h5py.File('Rorb-IRES2-Cre_590168381_590565013_new.nwb', "a") as f:
            f["general"]["institution"] = "Allen Institute"                
        
```

 I am left with one transpose on the fluorescence object that I can't correct. Whenever I create the file, it works, but it fails validation with the following error: 
```

0  ERROR
========

0.0  Rorb-IRES2-Cre_590168381_590565013_new.nwb: During io.read() - <class 'TypeError'>: Key '2e2456e5-c167-412b-a2be-ca9f9ca74fe8' is already in this dict. Cannot reset items in a LabelledDict. - 'None' object with name 'None'
       Message: Traceback (most recent call last):
  File "/Users/jerome.lecoq/opt/miniconda3/envs/nwb/lib/python3.10/site-packages/nwbinspector/nwbinspector.py", line 540, in inspect_nwb
    for inspector_message in run_checks(nwbfile=nwbfile, checks=checks):
  File "/Users/jerome.lecoq/opt/miniconda3/envs/nwb/lib/python3.10/site-packages/nwbinspector/nwbinspector.py", line 562, in run_checks
    for nwbfile_object in nwbfile.objects.values():
  File "/Users/jerome.lecoq/opt/miniconda3/envs/nwb/lib/python3.10/site-packages/pynwb/file.py", line 548, in objects
    self.all_children()
  File "/Users/jerome.lecoq/opt/miniconda3/envs/nwb/lib/python3.10/site-packages/pynwb/file.py", line 537, in all_children
    self.__obj[n.object_id] = n
  File "/Users/jerome.lecoq/opt/miniconda3/envs/nwb/lib/python3.10/site-packages/hdmf/utils.py", line 1025, in __setitem__
    raise TypeError("Key '%s' is already in this dict. Cannot reset items in a %s."
TypeError: Key '2e2456e5-c167-412b-a2be-ca9f9ca74fe8' is already in this dict. Cannot reset items in a LabelledDict.

```

@rly or @bendichter any clue?

**Comment by oruebel** [comment]
From the error, it looks like there are somehow to objects (e.g., TimeSeries) with the same object_id in the file. You could  try adding a call to ``nwbfile.generate_new_id()`` before you call the export to reset all object ids and see if that fixes the issues. However, I think this error likely indicates that there is some issue with the script itself in that maybe some ROIResponseSeries is being duplicated in the file with the same object_id.

**Comment by jeromelecoq** [comment]
Thanks for this suggestion, this does not fix this error.

**Comment by jeromelecoq** [comment]
I am suspecting this is related to the same rois table being referenced across Neuropil, Fluorescence and Deconvolved
```

Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (0, 0, 0), type "|u1">
  description: no description
  dimension: <HDF5 dataset "dimension": shape (2,), type "<i8">
  external_file: <StrDataset for HDF5 dataset "external_file": shape (1,), type "|O">
  format: external
  imaging_plane: ImagingPlane pynwb.ophys.ImagingPlane at 0x5798663872
Fields:
  conversion: 1.0
  description: standard
  device: Microscope pynwb.device.Device at 0x5798664256
Fields:
  description: My two-photon microscope
  manufacturer: The best microscope manufacturer

  excitation_lambda: 600.0
  imaging_rate: 30.0
  indicator: GCaMP
  location: V1
  optical_channel: (
    OpticalChannel <class 'pynwb.ophys.OpticalChannel'>
  )
  unit: meters

  offset: 0.0
  rate: 30.0
  resolution: -1.0
  starting_frame: [0]
  starting_time: 0.0
  starting_time_unit: seconds
  unit: unknown

Neuropil pynwb.ophys.Fluorescence at 0x5798666848
Fields:
  roi_response_series: {
    Neuropil <class 'pynwb.ophys.RoiResponseSeries'>
  }

Neuropil pynwb.ophys.RoiResponseSeries at 0x5798667952
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (1612, 114045), type "<f4">
  description: no description
  offset: 0.0
  rate: 30.0
  resolution: -1.0
  rois: rois <class 'hdmf.common.table.DynamicTableRegion'>
  starting_time: 0.0
  starting_time_unit: seconds
  unit: lumens

rois hdmf.common.table.DynamicTableRegion at 0x5798666800
    Target table: PlaneSegmentation pynwb.ophys.PlaneSegmentation at 0x5798667088

Deconvolved pynwb.ophys.Fluorescence at 0x5798665264
Fields:
  roi_response_series: {
    Deconvolved <class 'pynwb.ophys.RoiResponseSeries'>
  }

Deconvolved pynwb.ophys.RoiResponseSeries at 0x5798666512
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (1612, 114045), type "<f4">
  description: no description
  offset: 0.0
  rate: 30.0
  resolution: -1.0
  rois: rois <class 'hdmf.common.table.DynamicTableRegion'>
  starting_time: 0.0
  starting_time_unit: seconds
  unit: lumens

rois hdmf.common.table.DynamicTableRegion at 0x5798666800
    Target table: PlaneSegmentation pynwb.ophys.PlaneSegmentation at 0x5798667088

Fluorescence pynwb.ophys.Fluorescence at 0x5798665504
Fields:
  roi_response_series: {
    Fluorescence <class 'pynwb.ophys.RoiResponseSeries'>
  }

Fluorescence pynwb.ophys.RoiResponseSeries at 0x5798667184
Fields:
  comments: no comments
  conversion: 1.0
  data: <HDF5 dataset "data": shape (1612, 114045), type "<f4">
  description: no description
  offset: 0.0
  rate: 30.0
  resolution: -1.0
  rois: rois <class 'hdmf.common.table.DynamicTableRegion'>
  starting_time: 0.0
  starting_time_unit: seconds
  unit: lumens

rois hdmf.common.table.DynamicTableRegion at 0x5798666800
    Target table: PlaneSegmentation pynwb.ophys.PlaneSegmentation at 0x5798667088
```
