### ISSUE TITLE
`electrodes` column in `misc.Units.add_unit()` doesn't adhere to nwb-schema

### ISSUE THREAD

**Issue by bjhardcastle** [NeurodataWithoutBorders/pynwb#1787]
If I'm looking at the right thing, then the schema specifies the column as a `DynamicTableRegion` and the column in the units table should be a link to the electrodes table:
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.misc.yaml#L219-L222
```yaml
  - name: electrodes
    neurodata_type_inc: DynamicTableRegion
    doc: Electrode that each spike unit came from, specified using a DynamicTableRegion.
    quantity: '?'
```

...which doesn't match the accepted types in `add_unit()`:
https://github.com/NeurodataWithoutBorders/pynwb/blob/eb585063b3e035d68f206c49ff19200f9f25fa43/src/pynwb/misc.py#L189-L190

..and just to check that `DynamicTableRegion` isn't an `'array_data'` type:
```
Units.add_unit: incorrect type for 'electrodes' (got 'DynamicTableRegion', expected 'ndarray, list, tuple, Dataset, Array, StrDataset, HDMFDataset or AbstractDataChunkIterator')
```

Presumably this is expecting a sequence of integers, which are the indices of the corresponding rows in the electrodes table, but it's not clear: the description sounds more like links to the electrodes table.
