### ISSUE TITLE
[Docs]: Extra unsupplied attrs in `VoltageClampStimulusSeries`, merge inheritance behavior needs more documentation

### ISSUE THREAD

**Issue by sneakers-the-rat** [NeurodataWithoutBorders/pynwb#1954]
### What happened?

Validating `nwb_linkml` & `nwb_models` against live and synthetic data, and it looks like `VoltageClampStimulusSeries` adds additional attributes into the `data` dataset, and the validator doesn't catch it.

In `core` version `2.7.0`, [`VoltageClampStimulusSeries.data`](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/d65d42257003543c569ea7ac0cd6d7aee01c88d6/core/nwb.icephys.yaml#L188) is:

```yaml
  - name: data
    doc: Stimulus voltage applied.
    attributes:
    - name: unit
      dtype: text
      value: volts
      doc: Base unit of measurement for working with the data. which is fixed to 'volts'.
        Actual stored values are not necessarily stored in these units. To access the data in these units,
        multiply 'data' by 'conversion' and add 'offset'.
```

and yet my generated dataset has `conversion = 1.0`, `offset=0.0`, and `resolution=-1.0` in it.

This appears to come from how `PatchClampSeries.data` incorrectly specifies that `data` is a `TimeSeries.data`: https://github.com/NeurodataWithoutBorders/pynwb/blob/2d00afe30b3116c714e53a39522488e97c9160c5/src/pynwb/icephys.py#L93

despite no such `neurodata_type_inc` [existing in the schema](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/d65d42257003543c569ea7ac0cd6d7aee01c88d6/core/nwb.icephys.yaml#L15).

Unless it's the case that by doing `neurodata_type_inc` one is supposed to recursive *merge* all attributes in datasets and groups defined in inheriting classes, rather than overriding them, which would be... interesting. 

My MWE below is literally just following the docs example, so not too thrilling

### Steps to Reproduce

```python
from pynwb import NWBFile, NWBHDF5IO
from pynwb.icephys import VoltageClampStimulusSeries
from datetime import datetime
import h5py

nwbfile = NWBFile(session_description='', identifier='', session_start_time=datetime.now())
device = nwbfile.create_device(name="Heka ITC-1600")
electrode = nwbfile.create_icephys_electrode(
    name="elec0", description="a mock intracellular electrode", device=device
)

stimulus_template = VoltageClampStimulusSeries(
    name="ccst",
    data=[0, 1, 2, 3, 4],
    starting_time=0.0,
    rate=10e3,
    electrode=electrode,
    gain=0.02,
)
nwbfile.add_stimulus_template(stimulus_template)

with NWBHDF5IO('example.nwb', 'w') as io:
    io.write(nwbfile)

>>> h5f = h5py.File('example.nwb', 'r')

>>> print(dict(h5f.get('/stimulus/templates/ccst/data').attrs.items()))
{'conversion': 1.0, 'offset': 0.0, 'resolution': -1.0, 'unit': 'volts'}
```

### Operating System

macOS

### Python Executable

Python

### Python Version

3.11

### Package Versions

pynwb==2.8.1
hdmf==3.14.3
h5py==3.11.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you checked the [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues)?

**Comment by sneakers-the-rat** [comment]
I can keep checking for these mismatches if you want, since my models are literal transcriptions of the schema, but also don't want to generate too much noise or be annoying, so just lmk

Edit: I mean this in the sense of "I need to keep doing close reads of the schema because the models keep refusing to instantiate" not like "the models are perfect." Like "while im down here in the schema store yall want me to get anything" lol

**Comment by stephprince** [comment]
@sneakers-the-rat  I believe it is the case that `neurodata_type_inc` indicates that the `VoltageClampStimulusSeries` should inherit the specification for all attributes in datasets and groups of `TimeSeries`. The additional information specified in `VoltageClampStimulusSeries.data` is meant to refine the data specification from the base `TimeSeries.data` spec (in this case restricting the unit to volts). So it is expected that `VoltageClampStimulusSeries.data` would include the `conversion`, `offset`, and `resolution` attributes since it inherits these attributes from `TimeSeries`.

For the section of code you highlighted in `icephys.py` where the PatchClampSeries constructor can accept a `TimeSeries` type for the data argument, I think `TimeSeries` is a valid input for `PatchClampSeries.data` because of the option to have linked `TimeSeries`. See the `TimeSeries` constructor here: https://github.com/NeurodataWithoutBorders/pynwb/blob/2d00afe30b3116c714e53a39522488e97c9160c5/src/pynwb/base.py#L171-L172 where if the data argument is a `TimeSeries`, then that `TimeSeries` will be linked to so that the same data can be reused in multiple locations in the file.

**Comment by sneakers-the-rat** [comment]
ooh boy ok that's what i was afraid of. OK so just to be clear it's the case that if i do this:

```yaml
groups:
- neurodata_type_def: MyData
  datasets:
  - name: data
     attributes:
     - name: parent_attribute
       dtype: float32
       default_value: 1.0
- neurodata_type_def: MyChild
  neurodata_type_inc: MyData
  datasets:
  - name: data
    attributes:
    - name: parent_attribute
      dtype: text
```

that we would expect all unset attributes to merge down into the child class and so here the `default_value` of `MyChild.data.parent_attribute` should be `1.0`?

That is _not_ what i would have expected - i expect the inheritance from the parent class, but i did not expect that it would also recursively merge all properties, where even if i override a dataset, group, or attribute, the rest of the values come along with it. The docs could be clearer on this, and i am not sure that happens uniformly throughout the schema but i'll check

---

Re: being able to use a `TimeSeries` for `TimeSeries.data`, that's even more unexpected, since `TimeSeries.data` is a dataset and `TimeSeries` is a group, and i was unaware that there was a mechanism in the schema to do references like that - I thought that a `reference` dtype or `link` was the only way to do that. Is there any documentation in the schema for that behavior? When can I substitute a group for a dataset, is it just TimeSeries or is this a regular mechanism used throughout NWB?
