### ISSUE TITLE
Associate cluster waveforms and electrode table regions with unit times

### ISSUE THREAD

**Issue by NileGraddis** [NeurodataWithoutBorders/pynwb#431]
UnitTimes provide a nice way to store event times associated with sorted units. There should be a way to associate mean/std waveforms (such as those in ClusterWaveforms) as well as electrodes (such as those in ElectrodeTableRegion) to the units defined by a UnitTimes container.

Since UnitTimes supports simulated data and ophys data as well as ephys data, the solution to this problem should probably involve referencing units in UnitTimes from other containers rather than altering UnitTimes itself.

**Comment by ajtritt** [comment]
What about a type that maps between the different IDs? It could be a table with two columns. For example, in the ElectrodeTable to UnitTimes case, the first column would be an id from the electrode table and the second column would be an id from UnitTimes.unit_id.

**Comment by tjd2002** [comment]
I support a separate class to represent Units (independent of UnitTimes/ClusterWaveforms).And NB we definitely want to refer to electrodetableregions and not just electrodeids.

What is the reason to separate this list of Units from the UnitMetrics class as proposed at PR #435? Are there cases where there will not be a 1:1 correspondence between UnitMetrics and Units?

**Comment by NileGraddis** [comment]
The way that I am currently leaning towards implementing Units is as a group with two datasets:

1. a list of unit ids
2. a table of associations, with one column of unit ids and another of links, like this:
```
  - neurodata_type_def: UnitAssociations
    neurodata_type_inc: NWBData
    doc: table of unit associations
    attributes:
      - name: help
        doc: a help string
        dtype: text
        value: table of unit associations
    dtype:
      - name: unit_id
        doc: id of unit
        dtype: int
      - name: association
        doc: a reference
        dtype:
          target_type: NWBBaseType
          reftype: object
``` 

This would allow us to attach electrode groups, event times, waveforms and other data to units while preserving the type of the attached data. We could then units obtained from different modalities (ecephys, ophys, models) in a cohesive framework.

I think that @tjd2002's suggestion is reasonable. The UnitMetrics could be attached to the file as a subgroup of the Units
