### ISSUE TITLE
NWB Extensions tutorial has incorrect argument order in call to NWBAttributeSpec

### ISSUE THREAD

**Issue by jeffteeters** [NeurodataWithoutBorders/pynwb#502]
In the NWB Extensions tutorial, at:
https://pynwb.readthedocs.io/en/latest/tutorials/general/extensions.html#sphx-glr-tutorials-general-extensions-py

Parameters to NWBAttributeSpec should be:

`pynwb.spec.NWBAttributeSpec(name, doc, dtype, shape=None, dims=None, required=True, parent=None, value=None, default_value=None)`
(According to the API specification at:
http://pynwb.readthedocs.io/en/latest/pynwb.spec.html?highlight=NWBAttributeSpec)

But the call in the tutorial is:

`NWBAttributeSpec('trode_id', 'int', 'the tetrode id')`

(The doc and dtype are reversed).

This results in the following yaml file (mylab.extensions.yaml) being generated:

```
groups:
- attributes:
  - doc: int
    dtype: the tetrode id
    name: trode_id
  doc: A custom ElectricalSeries for my lab
  neurodata_type_def: TetrodeSeries
  neurodata_type_inc: ElectricalSeries
```

With the `doc` & `dtype` being reversed.
