### ISSUE TITLE
`ImageSeries.dimensions` should be `int`

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#512]
from the tutorial:
```python
image_series = TwoPhotonSeries(name='test_iS', source='Ca2+ imaging example', dimension=[2],
                               external_file=['images.tiff'], imaging_plane=imaging_plane,
                               starting_frame=[0], format='tiff', timestamps=list())
```

I think `dimensions` should be an `int`. It is `int` in [nwb-schema](https://github.com/NeurodataWithoutBorders/nwb-schema/blob/76fdcc0051568ed3ace184da751dc20d2d202407/core/nwb.image.yaml):

```yaml
    - rank
    doc: Number of pixels on x, y, (and z) axes.
    dtype: int32
    name: dimension
    quantity: '?'
    shape:
    - null
```
