### ISSUE TITLE
validator fails to enforce required ProcessingModule

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/pynwb#910]
### Steps to Reproduce
```python
from pynwb.spec import NamespaceBuilder, NWBGroupSpec

name = 'test'

ns_builder = NamespaceBuilder(name=name, version='0.1', doc='doc')

# import the core types used by this extension
for ndtype in ('ElectricalSeries', 'ProcessingModule', 'LFP', 'NWBDataInterface',
               'TimeSeries', 'NWBContainer', 'NWBFile'):
    ns_builder.include_type(ndtype, namespace='core')

nwbfile = NWBGroupSpec(neurodata_type_inc='NWBFile', name='root', doc='doc')
processing = nwbfile.add_group(name='processing', doc='doc')
processing.add_group(neurodata_type_inc='ProcessingModule', name='not_present', doc='doc', quantity=1)


ns_path = name + '.namespace.yaml'
ext_source = name + '.extensions.yaml'

# Export
ns_builder.add_spec(ext_source, nwbfile)
ns_builder.export(ns_path)
```

```bash
python -m pynwb.validate -p test.namespace.yaml some_file.nwb
```
yields no errors

test.extensions.yaml:
```yaml
groups:
- neurodata_type_inc: NWBFile
  name: root
  doc: doc
  groups:
  - name: processing
    doc: doc
    groups:
    - neurodata_type_inc: ProcessingModule
      name: not_present
      doc: doc
```

test.namespace.yaml:
```yaml
namespaces:
- doc: schema for importing into brainstorm
  name: test
  schema:
  - data_types:
    - ElectricalSeries
    - ProcessingModule
    - LFP
    - NWBDataInterface
    - TimeSeries
    - NWBContainer
    - NWBFile
    namespace: core
  - source: test.extensions.yaml
  version: '0.1'
```

When `some_file.nwb` is a file without a `ProcessingModule` named `not_present`, the validator should report an error.

## Checklist

- [x] Have you ensured the feature or change was not already [reported](https://github.com/NeurodataWithoutBorders/pynwb/issues/) ?
- [x] Have you included a brief and descriptive title?
- [x] Have you included a clear description of the problem you are trying to solve?
- [x] Have you included a minimal code snippet that reproduces the issue you are encountering?
- [x] Have you checked our [Contributing](https://github.com/NeurodataWithoutBorders/pynwb/blob/dev/docs/CONTRIBUTING.rst) document?
