### ISSUE TITLE
Ophys default values not used in pynwb

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/pynwb#974]
`ImagingPlane` uses None as default values for `ImagingPlane.manifold.conversion` and `ImagingPlane.manifold.unit` when they should be `1.0` and `'Meter'`

## Bug

The schema says:
```yaml
  - name: manifold
    dtype: float32
    doc: 'Physical position of each pixel. COMMENT: ''xyz'' represents the position
      of the pixel relative to the defined coordinate space'
    attributes:
    - name: conversion
      dtype: float
      doc: Multiplier to get from stored values to specified unit (e.g., 1e-3 for
        millimeters)
      default_value: 1.0
      required: false
    - name: unit
      dtype: text
      doc: Base unit that coordinates are stored in (e.g., Meters)
      default_value: Meter
      required: false
```

but `ImagingPlane` says:
```
class ImagingPlane(NWBContainer):
    @docval({'name': 'name', 'type': str, 'doc': 'the name of this electrode'},
            ...
            {'name': 'conversion', 'type': float,
             'doc': 'Multiplier to get from stored values to specified unit (e.g., 1e-3 for millimeters)',
             'default': None},
            {'name': 'unit', 'type': str, 'doc': 'Base unit that coordinates are stored in (e.g., Meters).',
             'default': None},
```

PyNWB defaults should be updated.
